spring:
  profiles:
    group:
      local:
        - app
        - domain
      dev:
        - app-dev
        - domain-dev
    active: local

  config:
    import: classpath:application-dev.yml

server:
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 400
      min-spare: 20

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[hikaricp.connections.acquire]": true

---

spring:
  config:
    activate:
      on-profile: local
