plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.5.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
    }
}
rootProject.name = 'monsing'
include 'domain'
include 'app'
include 'api'
include 'chat'
include 'chat-worker'
include 'auth'

