spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      host: ENC(uYqaGXQm9IZ8SUFYVAO6i8l6jslWmtdC)
      port: ENC(AmGJ5jY3T+1qsG97auYUeA==)
      username:
      password:

  datasource:
    url: ENC(E4yKRAjTOQzpiw4lh7Yj0KPfU4DEc2+JmdawQayQaThho5RuzJq2norhrQj8V0Xo)
    username: ENC(Y0JP21hSdSckIOfrmdXHYw==)
    password: ENC(5ZfpUHvNEFFzkJgyjLhjEETADLVKWsIF)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
