openapi: 3.0.0
info:
  title: 선생님 API
  version: 1.0.0
  description: 선생님 관련 API

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /teachers:
    post:
      summary: 선생님 계정 생성
      security:
        - BearerAuth: [ ]
      operationId: createTeacher
      tags:
        - Teacher
      requestBody:
        description: 선생님 계정 생성에 필요한 정보
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeacherCreateRequest'
      responses:
        '200':
          description: 성공
        '400':
          description: 잘못된 요청

    get:
      summary: 선생님 목록 조회
      operationId: readTeachers
      tags:
        - Teacher
      parameters:
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
          description: 한 번에 조회할 선생님 수
        - name: lastId
          in: query
          required: false
          schema:
            type: integer
            format: int64
            default: 0
          description: 커서 기반 페이징 - 마지막으로 받은 선생님 ID (0이면 처음부터 조회)
      responses:
        '200':
          description: 선생님 목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeacherOverviewResponse'
        '400':
          description: 잘못된 요청

  /teachers/{id}:
    get:
      summary: 선생님 요약 정보
      description: 선생님 ID로 요약 정보 조회
      operationId: getTeacherOverview
      tags:
        - Teacher
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: 선생님 ID
      responses:
        '200':
          description: 선생님 상세 정보 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeacherOverviewResponse'
        '400':
          description: 잘못된 요청

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # 선생님 계정 생성 요청
    TeacherCreateRequest:
      type: object
      properties:
        name:
          type: string
          description: 선생님 이름
        gender:
          $ref: '#/components/schemas/Gender'
      required:
        - name
        - gender

    # 선생님 조회 응답
    TeacherResponse:
      type: object
      properties:
        id:
          type: integer
          description: 선생님 ID
        name:
          type: string
          description: 선생님 이름
        experience:
          type: integer
          description: 선생님 경력
        profileImage:
          type: string
          description: 선생님 프로필 이미지 URL
        summary:
          type: string
          description: 선생님 한줄 소개
        favorite:
          type: boolean
          description: 즐겨찾기 여부
        verified:
          type: boolean
          description: 선생님 인증 여부
        rating:
          type: number
          description: 선생님 평점
        reviewCount:
          type: integer
          description: 선생님 리뷰 수

    # 선생님 상세 정보 응답
    TeacherOverviewResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 식별자
        name:
          type: string
          description: 이름
        profileImage:
          type: string
          description: 프로필 이미지 URL
        summary:
          type: string
          description: 한줄 설명
        verified:
          type: boolean
          description: 인증 여부
        description:
          type: string
          description: 상세 설명
        careers:
          type: array
          items:
            $ref: '#/components/schemas/CareerResponse'

        portfolios:
          type: array
          items:
            $ref: '#/components/schemas/PortfolioResponse'

      required:
        - id
        - name
        - verified
        - careers
        - portfolios

    # 경력 응답
    CareerResponse:
      type: object
      properties:
        detail:
          type: string
          description: 경력 상세 내용 (예, 학원명과 기간)
        period:
          type: string
          description: 경력 기간 (예, "2023~2024")

    # 포트폴리오 응답
    PortfolioResponse:
      type: string
      description: 포트폴리오 URL 리스트 (예, "port.google.com/portport")

    # 리뷰 생성 요청
    ReviewCreateRequest:
      type: object
      properties:
        detail:
          type: string
          description: 리뷰 내용
        ratings:
          type: array
          description: 평점 목록
          items:
            $ref: '#/components/schemas/RatingDto'
      required:
        - detail
        - ratings

    # 평가 DTO
    RatingDto:
      type: object
      properties:
        ratingType:
          type: string
          description: 평가 유형
        score:
          type: integer
          description: 평가 점수

    # 리뷰 요약 응답
    ReviewSummaryResponse:
      type: object
      properties:
        averageScore:
          type: number
          description: 평균 평점
        reviewCount:
          type: integer
          description: 리뷰 개수
        ratings:
          items:
            $ref: '#/components/schemas/RatingDto'

    # 리뷰 응답
    ReviewResponse:
      type: object
      properties:
        id:
          type: integer
          description: 리뷰 ID
        writerName:
          type: string
          description: 리뷰 작성자 이름
        detail:
          type: string
          description: 리뷰 내용
        createdAt:
          type: string
          format: date-time
          description: 리뷰 작성 시간
        ratings:
          type: array
          items:
            $ref: '#/components/schemas/RatingDto'

    # 수업 응답
    PrevCourseResponse:
      type: object
      properties:
        id:
          type: integer
          description: 강좌 ID
        title:
          type: string
          description: 강좌 제목

    ClassResponse:
      type: object
      properties:
        schedule:
          $ref: '#/components/schemas/ScheduleResponse'
        remain:
          type: integer
          description: 남은 수업 수(?)
        student:
          $ref: '#/components/schemas/StudentResponse'

    # 스케줄 응답
    ScheduleResponse:
      type: object
      properties:
        day:
          type: string
          description: 요일 (2024-01-20)
        startTime:
          type: string
          description: 시작 시간
        endTime:
          type: string
          description: 종료 시간

    # 학생 응답
    StudentResponse:
      type: object
      properties:
        id:
          type: integer
          description: 학생 ID
        name:
          type: string
          description: 학생 이름

    Gender:
      type: string
      description: 선생님 성별
      enum:
        - MALE
        - FEMALE
        - OTHER

# todo : course, class 리스펀스 구분
