spring:
  profiles:
    group:
      local:
        - app
        - domain
      dev:
        - app-dev
        - domain-dev
    active: local
  docker:
    compose:
      enabled: false
  jpa:
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: prometheus

---

spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop
      stop:
        command: down

aws:
  cloudfront-url: https://sadniasdksmkadmiqiq.com

logging:
  discord:
    webhook-url:
