spring:
  profiles:
    group:
      local:
        - app
        - domain
      dev:
        - app-dev
        - domain-dev
    active: local
  docker:
    compose:
      enabled: false
  jpa:
    open-in-view: false
server:
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 400
      min-spare: 20

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[hikaricp.connections.acquire]": true

---

spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop
      stop:
        command: down

aws:
  cloudfront-url: https://sadniasdksmkadmiqiq.com

logging:
  discord:
    webhook-url:
